"""MegaCache public API."""

from .cluster import (
    ClusterNode,
    ClusterStorage,
    ConsistencyProfile,
    ConsistentHashRing,
    FenceError,
    FenceToken,
    NodeIdentity,
    QuorumError,
    RebalanceError,
    RebalancePlan,
    SnapshotBackpressure,
    SnapshotError,
    SnapshotManifest,
    SnapshotReceiver,
    SnapshotSession,
)
from .engine import CacheEngine, CacheResult
from .origin import (
    BreakerState,
    CircuitOpen,
    HTTPOrigin,
    OriginCache,
    OriginError,
    OriginFetchResult,
    OriginOverloaded,
    OriginPolicyError,
    OriginResponse,
    OriginUnavailable,
    load_origin_definitions,
    validate_origin_path,
)
from .storage import StorageBackend, StorageEntry

__all__ = [
    "CacheEngine",
    "CacheResult",
    "BreakerState",
    "CircuitOpen",
    "ClusterNode",
    "ClusterStorage",
    "ConsistencyProfile",
    "ConsistentHashRing",
    "FenceError",
    "FenceToken",
    "NodeIdentity",
    "HTTPOrigin",
    "OriginCache",
    "OriginError",
    "OriginFetchResult",
    "OriginOverloaded",
    "OriginPolicyError",
    "OriginResponse",
    "OriginUnavailable",
    "QuorumError",
    "RebalanceError",
    "RebalancePlan",
    "SnapshotBackpressure",
    "SnapshotError",
    "SnapshotManifest",
    "SnapshotReceiver",
    "SnapshotSession",
    "StorageBackend",
    "StorageEntry",
    "load_origin_definitions",
    "validate_origin_path",
]
__version__ = "0.6.0"
